### ISSUE TITLE
Cannot find module 'eslint-config-wesbos' Laravel local install

### ISSUE THREAD

**Issue by aminraeisi** [wesbos/eslint-config-wesbos#29]
I did all the local installation guide and now I get this error if I run the `eslint .` in terminal. But in VSCode it just formats it with another setting which I don't no where it is and it just ignores my `.eslintrc` file completely. However, when I run it in terminal it shows the following:

```
Cannot find module 'eslint-config-wesbos'
Referenced from: /home/amin/Code/prototype/prent/alpha/.eslintrc
Error: Cannot find module 'eslint-config-wesbos'
Referenced from: /home/amin/Code/prototype/prent/alpha/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:471:25)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:542:26)
    at configExtends.reduceRight (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/usr/local/lib/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/usr/local/lib/node_modules/eslint/lib/config.js:180:43)
```

**Comment by robintom** [comment]
The problem is the ESLint Package extension is unable to find or load the eslint-config-wesbos module. I think it has something to do with breaking changes on one of the eslint dependency packages that @wesbos uses for his module.

It may have something to do with #28

**Comment by robintom** [comment]
@aminraeisi Do you has eslint.nodePath set? If not , go to your settings.json (File > Preferences > Settings) and add the below line :

`"eslint.nodePath" : "_path to your local node_modules folder_"`

If you have eslint installed and configured globally , point the path to your global node_modules installation path (Use npm list -g | head -n 1 to find your global path) or if its a local installation point to your node_modules in the project directory. I think this would fix your issue.

**Comment by aminraeisi** [comment]
@robintom Thanks for the reply. As I mentioned, I get the error in terminal (ubuntu terminal) so the problem is not with VSCode only. I tried your solution and it did not solve it.

**Comment by aminraeisi** [comment]
I found the solution here: https://github.com/standard/eslint-config-standard/issues/84#issuecomment-315129706
