### ISSUE TITLE
Eslint failed to load Wesbos with Gatsby

### ISSUE THREAD

**Issue by Nierusan** [wesbos/eslint-config-wesbos#34]
Hi !

I don't know why, but recently your setting doesn't work anymore with Gatsby... Outside Gatsby, the plugin still works.

 This is the error I got :

`ESLint: Failed to load config "wesbos" to extend from. Referenced from: /Users/$USER/.eslintrc. Please see the 'ESLint' output channel for details.`

And the terminal Output
```
[Info  - 23:33:00] ESLint server stopped.
[Info  - 23:33:00] ESLint server running in node v10.11.0
[Info  - 23:33:00] ESLint server is running.
[Info  - 23:33:00] ESLint library loaded from: /Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/api.js
[Error - 23:33:00] ESLint stack trace:
[Error - 23:33:00] Error: Failed to load config "wesbos" to extend from.
Referenced from: /Users/$user/.eslintrc
    at configMissingError (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:712:23)
    at ConfigArrayFactory._loadExtends (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:617:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:547:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
    at ConfigArrayFactory.loadInDirectory (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:400:16)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:381:55)
[Error - 23:35:38] ESLint stack trace:
[Error - 23:35:38] Error: Failed to load config "wesbos" to extend from.
Referenced from: /Users/$user/.eslintrc
    at configMissingError (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:712:23)
    at ConfigArrayFactory._loadExtends (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:617:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:547:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
    at ConfigArrayFactory.loadInDirectory (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/config-array-factory.js:400:16)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/$user/working/gatsby/Diametal/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:381:55)
```

**Comment by petercr** [comment]
That's strange, I use it all the time with Gatsby 😎 
Although I usually run it just once per project, and it installs the dev dependencies. 
Maybe try re-running `npm install` and see if that fixes the problem 👍 

Maybe a copy of the `package.json` file too, to make sure everything installed correctly

**Comment by smakosh** [comment]
Works fine for me with Gatsby, try to follow what the ESLint console is recommending, often time I have to install `eslint-plugin-html` to make it work

Hey @wesbos should I open a PR adding `eslint-plugin-html` as a dev dep?

**Comment by Asjas** [comment]
The `eslint-plugin-html` plugin has been added as a `devDependency` and `peerDependency` for some time now. If you install the latest version of this config it works and you'll no longer get the `failed to extend config "wesbos"` error message. 😄
