### ISSUE TITLE
Cant get it to work - Noob help needed 25 $ TIP

### ISSUE THREAD

**Issue by Taxick** [wesbos/eslint-config-wesbos#54]
### I Send 25$ for a cup coffee (paypal) to the person that can fix the problem for me!

Hi, 

First, your script looks very nice, but I can't get it to work. - Im a Noob :)

### Btw I'm running "Ubuntu Budgie 20.04"

I have followed the "Local / Per Project Install" guide you have here a GitHub. / this youtube: https://www.youtube.com/watch?v=lHAeK8t94as&t

### It gives me an NPM WARN when I install the script! - Here is the text from the console!

```
thomas@Dragon:~/Skrivebord/test$ npx install-peerdeps --dev eslint-config-wesbos
install-peerdeps v2.0.3
Installing peerdeps for eslint-config-wesbos@latest.
npm install eslint-config-wesbos@0.0.20 babel-eslint@^9.0.0 eslint@^6.1.0 eslint-config-airbnb@^18.0.0 eslint-config-prettier@^4.1.0 eslint-plugin-html@^5.0.3 eslint-plugin-import@^2.18.0 eslint-plugin-jsx-a11y@^6.2.3 eslint-plugin-prettier@^3.0.1 eslint-plugin-react@^7.14.2 eslint-plugin-react-hooks@^1.4.0 prettier@^1.16.4 --save-dev --registry https://registry.npmjs.org


> core-js-pure@3.6.5 postinstall /home/thomas/Skrivebord/test/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ eslint-plugin-prettier@3.1.4
+ eslint-plugin-jsx-a11y@6.3.1
+ eslint-config-airbnb@18.2.0
+ eslint-config-prettier@4.3.0
+ babel-eslint@9.0.0
+ eslint-plugin-react@7.20.6
+ eslint-plugin-import@2.22.0
+ eslint-plugin-html@5.0.5
+ eslint@6.8.0
+ prettier@1.19.1
+ eslint-plugin-react-hooks@1.7.0
+ eslint-config-wesbos@0.0.20
added 259 packages from 181 contributors and audited 259 packages in 7.352s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

SUCCESS eslint-config-wesbos
  and its peerDeps were installed successfully.
thomas@Dragon:~/Skrivebord/test$ 

```
### But the problem is, I get an error when I run: "npm run lint:fix" from CLI

```
thomas@Dragon:~/Skrivebord/test$ npm run lint:fix

> test@1.0.0 lint:fix /home/thomas/Skrivebord/test
> eslint . --fix

Error: Failed to load plugin 'html' declared in '.eslintrc » eslint-config-wesbos': eslint-plugin-html error: It seems that eslint is not loaded.
If you think this is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues

In the report, please include *all* those informations:

* ESLint version: 6.8.0
* ESLint path: /home/thomas/Skrivebord/test/node_modules/eslint/lib/api.js
* Plugin version: 5.0.5
* Plugin inclusion paths: /home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/config-array-factory.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/cli-engine.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/index.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli.js, /home/thomas/Skrivebord/test/node_modules/eslint/bin/eslint.js
* NodeJS version: v10.19.0
* CLI arguments: ["/usr/bin/node","/home/thomas/Skrivebord/test/node_modules/.bin/eslint",".","--fix"]
* Content of your lock file (package-lock.json or yarn.lock) or the output of `npm list`
* How did you run ESLint (via the command line? an editor plugin?)
* The following stack trace:
    at iterateESLintModules (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:98:7)
    at Object.<anonymous> (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:25:1)
    at Module._compile (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at ConfigArrayFactory._loadPlugin (/home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)


      
    at iterateESLintModules (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:83:11)
    at Object.<anonymous> (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:25:1)
    at Module._compile (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at ConfigArrayFactory._loadPlugin (/home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@1.0.0 lint:fix: `eslint . --fix`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the test@1.0.0 lint:fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2020-08-17T16_27_44_999Z-debug.log

```

### Here is the above log from: /home/thomas/.npm/_logs/2020-08-17T16_27_44_999Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'lint:fix' ]
2 info using npm@6.14.7
3 info using node@v10.19.0
4 verbose run-script [ 'prelint:fix', 'lint:fix', 'postlint:fix' ]
5 info lifecycle test@1.0.0~prelint:fix: test@1.0.0
6 info lifecycle test@1.0.0~lint:fix: test@1.0.0
7 verbose lifecycle test@1.0.0~lint:fix: unsafe-perm in lifecycle true
8 verbose lifecycle test@1.0.0~lint:fix: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/thomas/Skrivebord/test/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/>
9 verbose lifecycle test@1.0.0~lint:fix: CWD: /home/thomas/Skrivebord/test
10 silly lifecycle test@1.0.0~lint:fix: Args: [ '-c', 'eslint . --fix' ]
11 silly lifecycle test@1.0.0~lint:fix: Returned: code: 2  signal: null
12 info lifecycle test@1.0.0~lint:fix: Failed to exec lint:fix script
13 verbose stack Error: test@1.0.0 lint:fix: `eslint . --fix`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid test@1.0.0
15 verbose cwd /home/thomas/Skrivebord/test
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "lint:fix"
18 verbose node v10.19.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 2
22 error test@1.0.0 lint:fix: `eslint . --fix`
22 error Exit status 2
23 error Failed at the test@1.0.0 lint:fix script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

And I have also try to run  **eslint --fix** in VS: Code! (CTRL + SHIFT + P) I only get this error https://i.imgur.com/jGBpdWW.png

The code did not change!

I have tried to reinstall VS: Code, and disable all plugins - I have only "eslint" installed

Btw, I have tried to delete my test folder ~/Skrivebord/test and start over again

**And here is another log file.**

```
 info it worked if it ends with ok
 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'lint', 'fix' ]
 info using npm@6.14.7
 info using node@v10.19.0
 verbose run-script [ 'prelint', 'lint', 'postlint' ]
 info lifecycle test@1.0.0~prelint: test@1.0.0
 info lifecycle test@1.0.0~lint: test@1.0.0
 verbose lifecycle test@1.0.0~lint: unsafe-perm in lifecycle true
 verbose lifecycle test@1.0.0~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/thomas/Skrivebord/test/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
 verbose lifecycle test@1.0.0~lint: CWD: /home/thomas/Skrivebord/test
 silly lifecycle test@1.0.0~lint: Args: [ '-c', 'eslint . "fix"' ]
 silly lifecycle test@1.0.0~lint: Returned: code: 2  signal: null
 info lifecycle test@1.0.0~lint: Failed to exec lint script
 verbose stack Error: test@1.0.0 lint: `eslint . "fix"`
 verbose stack Exit status 2
 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
 verbose stack     at EventEmitter.emit (events.js:198:13)
 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
 verbose stack     at ChildProcess.emit (events.js:198:13)
 verbose stack     at maybeClose (internal/child_process.js:982:16)
 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
 verbose pkgid test@1.0.0
 verbose cwd /home/thomas/Skrivebord/test
 verbose Linux 5.4.0-42-generic
 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "lint" "fix"
 verbose node v10.19.0
 verbose npm  v6.14.7
 error code ELIFECYCLE
 error errno 2
 error test@1.0.0 lint: `eslint . "fix"`
 error Exit status 2
 error Failed at the test@1.0.0 lint script.
 error This is probably not a problem with npm. There is likely additional logging output above.
 verbose exit [ 2, true ]
```

### My .eslintrc file looks like this:

```
{
  "extends": [
    "wesbos"
  ]
}
```
### My package.json file looks like this:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
  "lint": "eslint .",
  "lint:fix": "eslint . --fix"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-config-wesbos": "0.0.20",
    "eslint-plugin-html": "^5.0.5",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^1.7.0",
    "prettier": "^1.19.1"
  }
}

```
### My settings.json looking like this:

```
{
    "notebook.kernelProviderAssociations": [
    
    ]
    // These are all my auto-save configs
    "eslint.autoFixOnSave": true,
    // turn it off for JS and JSX, we will do this via eslint
    "[javascript]": {
        "editor.formatOnSave": false
    },
    "[javascriptreact]": {
        "editor.formatOnSave": false
    },
    // tell the ESLint plugin to run on save
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    // Optional BUT IMPORTANT: If you have the prettier extension enabled for other languages like CSS and HTML, turn it off for JS since we are doing it through Eslint already
    "prettier.disableLanguages": [
        "javascript",
        "javascriptreact"
    ],
}
```
### My test.js I try to test with looks like this:

function sayHi  (       name        ) {
    var age=10;
}   

let age=12;

var things = ['cool'], "doubleee!!!" ];

**If I run this command: npm list -g | head -n 1**

```
thomas@Dragon:~/Skrivebord/test$ npm list -g | head -n 1
/usr/local/lib
npm ERR! peer dep missing: eslint@^5.16.0 || ^6.8.0 || ^7.2.0, required by eslint-config-airbnb-base@14.2.0
npm ERR! peer dep missing: eslint@>=6.2.2, required by eslint-config-standard@14.1.1
npm ERR! peer dep missing: eslint@>=5.16.0, required by eslint-plugin-node@11.1.0
npm ERR! peer dep missing: eslint@>=5.0.0, required by eslint-plugin-standard@4.0.1
npm ERR! peer dep missing: eslint-plugin-import@^2.21.2, required by eslint-config-airbnb-base@14.2.0
npm ERR! peer dep missing: eslint-plugin-import@>=2.18.0, required by eslint-config-standard@14.1.1
npm ERR! peer dep missing: eslint@>=4.19.1, required by eslint-plugin-es@3.0.1
thomas@Dragon:~/Skrivebord/test$ 

```
^^ Maybe its the problem? But how to fix this??

Kind regards 

Thomas aka Taxick

### I Send 25$ for a cup coffee (paypal) to the person that can fix the problem for me!

**Comment by Taxick** [comment]
I Send 25$ (paypal) to the person that can fix the problem for me!

**Comment by Asjas** [comment]
@Taxick You need to update the `eslint-plugin-html` package to `6.0.0` (minimum) or `6.0.3` (which is the latest) to fix the error message where is says `html package is missing from eslint-plugin-html`.

I'm still looking into what plugin or config was updated to cause this, but for now you can update the `eslint-plugin-html` package and the error will disappear 🙂

**Comment by wesbos** [comment]
@Asjas thanks a ton for looking into this. I did just update the Eslint version - maybe that is it? Could you PR to update that package?

**Comment by Asjas** [comment]
Sure - will do 👍

**Comment by wesbos** [comment]
Should be fixed in eslint-config-wesbos@0.0.21

**Comment by Taxick** [comment]
Hi @wesbos and @Asjas 

Thanks for your help - Both of you

I have tried to uninstall, and reinstall! the script!

First: npm remove --global eslint-config-wesbos babel-eslint eslint eslint-config-prettier eslint-config-airbnb eslint-plugin-html eslint-plugin-prettier eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react prettier eslint-plugin-react-hooks

And then: npx install-peerdeps --dev eslint-config-wesbos

But I still get this error when I try to use: npm run lint:fix

Maybe I'm doing something wrong? Can you guide me? I'm a NOOB! - Sorry

```
thomas@Dragon:~/Skrivebord/test$ npm run lint:fix

> test@1.0.0 lint:fix /home/thomas/Skrivebord/test
> eslint . --fix

Error: Failed to load plugin 'html' declared in '.eslintrc » eslint-config-wesbos': eslint-plugin-html error: It seems that eslint is not loaded.
If you think this is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues

In the report, please include *all* those informations:

* ESLint version: 6.8.0
* ESLint path: /home/thomas/Skrivebord/test/node_modules/eslint/lib/api.js
* Plugin version: 5.0.5
* Plugin inclusion paths: /home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/config-array-factory.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/cli-engine.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/index.js, /home/thomas/Skrivebord/test/node_modules/eslint/lib/cli.js, /home/thomas/Skrivebord/test/node_modules/eslint/bin/eslint.js
* NodeJS version: v10.19.0
* CLI arguments: ["/usr/bin/node","/home/thomas/Skrivebord/test/node_modules/.bin/eslint",".","--fix"]
* Content of your lock file (package-lock.json or yarn.lock) or the output of `npm list`
* How did you run ESLint (via the command line? an editor plugin?)
* The following stack trace:
    at iterateESLintModules (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:98:7)
    at Object.<anonymous> (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:25:1)
    at Module._compile (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at ConfigArrayFactory._loadPlugin (/home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)


      
    at iterateESLintModules (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:83:11)
    at Object.<anonymous> (/home/thomas/Skrivebord/test/node_modules/eslint-plugin-html/src/index.js:25:1)
    at Module._compile (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/thomas/Skrivebord/test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at ConfigArrayFactory._loadPlugin (/home/thomas/Skrivebord/test/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@1.0.0 lint:fix: `eslint . --fix`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the test@1.0.0 lint:fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2020-08-17T17_02_53_357Z-debug.log
thomas@Dragon:~/Skrivebord/test$ 
```

**Comment by Asjas** [comment]
Hi @Taxick

Sorry - it's fixed in `0.0.22` 😄 . I only updated the version in the `devDependency` section and I forgot to update the `peerDendendency`. I just tested locally by running `npx install-peerdeps eslint-config-wesbos` and it's now installing the right versions and it works now.

Can you try again? Thanks.

**Comment by Taxick** [comment]
Hi, @Asjas 

Prettier doesn't seams to fix my bug .js file..

And maybe a stupid question - Will I need to install "prettier" packet and "eslint" packet?

Thanks

**Comment by Asjas** [comment]
You will have prettier installed as a npm package since it exists in the `eslint-config-wesbos` package. You can check your `package.json` file and you'll see it there.

Did you setup VS Code? https://github.com/wesbos/eslint-config-wesbos#with-vs-code

**Comment by Taxick** [comment]
Hey @Asjas 

I have setup the code in settings.json - yes :)

Will prettier dont work on .js files? 

And please send me a msg, with you paypal, and i will send you a cup of coffie :)

**Comment by Asjas** [comment]
Prettier will work on `.js` files, but how are you running prettier? What command or npm script you are using?

In this eslint config that Wes created he adds prettier as a plugin _into_ eslint. So if you run `eslint . --fix` it runs eslint and then prettier automatically. 
https://github.com/wesbos/eslint-config-wesbos/blob/master/.eslintrc.js#L137

>And please send me a msg, with you paypal, and i will send you a cup of coffie :)

No need to pay 😄 , I fixed the issue earlier this morning in Wes's slack and just copied the solution here.

**Comment by Taxick** [comment]
Hey @Asjas 

I have the folloing code in my test.js

```
function sayHi  (        name        ) {
    var age=10;
}   
en
let age =  12;

var things = ['cool'], "doubleee!!!" ];
```

I run "eslint . --fix" but prettier don't seams to fix the spaces for example!

**Comment by Asjas** [comment]
Yeah I copied the code and it doesn't work with me. The issue is this line

```js
var things = ['cool'], "doubleee!!!" ];
```
It's incorrect JavaScript due to the syntax in that line of code and it's causing eslint to not format the code.

Using this code alone I get the formatting to work and it changes both `var` and `let` statements to `const`.

_this_
```js
function sayHi  (        name        ) {
    var age=           10
}

let age =  12
```
_becomes this_
```js
function sayHi(name) {
  const age = 10;
}

const age = 12;
```

**Comment by Taxick** [comment]
Hey @Asjas 

Thanks a lot for your big help. It really helps me a lot. 

I works now :) You must have a great day :+1:

I close the post now :)

Regards

Thomas
