### ISSUE TITLE
Failed With Code 7

### ISSUE THREAD

**Issue by TrafalgarWaterDLaw** [wesbos/eslint-config-wesbos#92]
Error: EPERM: operation not permitted, mkdir 'C:\Users\Mr'
TypeError: Cannot read property 'get' of undefined
    at errorMessage (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-message.js:38:39)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:201:13)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:171:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\←[4mnpm←[24m\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\←[4mnpm←[24m\lib\utils\error-handler.js:216:3)
←[90m    at process.emit (events.js:321:20)←[39m
←[90m    at process._fatalException (internal/process/execution.js:164:25)←[39m
Install for [ 'install-peerdeps@latest' ] failed with code 7

Each time I have attempted to try running the command, I am hitting this wall.

**Comment by Asjas** [comment]
@TrafalgarWaterDLaw Your issue seems to be caused by your Windows username having multiple words which contains spaces, the `npx` command has issues on Windows with those types of usernames. 

I'll post a solution here that you can use for `npx` 🙂

```
if you want to use current path that has space in username
"C:\Users\Firstname Lastname\AppData\Roaming\npm-cache"  
you can replace the string after space with "~1"
```

Example command:
```sh
npm config set cache "C:\Users\Firstname~1\AppData\Roaming\npm-cache" --global
```

https://github.com/zkat/npx/issues/146#issuecomment-384019497

**Comment by TrafalgarWaterDLaw** [comment]
Thanks
